swagger: '2.0'
info:
  description: test
  version: 1
  title: test
basePath: /test
schemes:
  - https
security:
  - HTTP_BASIC: []
  - TENANT_ID: []
  - AUTHENTICATION_TOKEN: []
paths:
  '/testapi/{id}':
    $ref: 'testapi/api.yaml'

securityDefinitions:
  HTTP_BASIC:
    type: basic
